name: transformer
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.12.12
  - matplotlib=3.10.8
  - pandas=2.3.3
  - numpy=2.3.1
  - pytorch-cuda=12.1
  - pytorch=2.5.1
  - conda-forge::scipy=1.17.0
  - scikit-learn
  - pyyaml
  - tqdm
  - pytest
  - pip
  - pip:
      - wandb
      - xgboost
